version: "3.4"
services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
       MYSQL_DATABASE: multe-pass
       MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - ./database/multe-pass.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app_network

  api:
    restart: always
    container_name: api
    build:
      dockerfile: Dockerfile
      context: "./api"
    depends_on:
      - db
    volumes:
      - ./api:/app
    ports:
      - 9103:9103
    networks:
      - app_network


  web:
    image: php:7.4-apache
    container_name: php-apache
    volumes:
      - ./frontend:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
      driver: bridge
